version: 2.1
jobs:
  building:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: "Installing Dependencies"
          command: |
            apt update
            apt install -y docker.io curl zip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
      - run:
          name: "Say hello"
          command: aws --help

workflows:
  nclouds:
    jobs:
      - building
