version: 2.1
jobs:
  building:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: "Installing Dependencies"
          command: |
            apt update
            apt install -y docker.io curl zip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
      - run:
          name: "Auth"
          command: aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 450183644535.dkr.ecr.us-west-2.amazonaws.com
      - setup_remote_docker
      - run:
          name: "Build"
          command: |
            docker build -t color .
            docker tag color 450183644535.dkr.ecr.us-west-2.amazonaws.com/nclouds:latest
      - run:
          name: "Pushing Image"
          command: docker push 450183644535.dkr.ecr.us-west-2.amazonaws.com/nclouds:latest
workflows:
  nclouds:
    jobs:
      - building
